### PR TITLE
Rebase to hippie (I think)

### PR DESCRIPTION
**Pull request by GuyonBroadway**
it compiles and it seems to run,

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
actually hold up a sec, I think the lobby music is borked

**Comment by GuyonBroadway** [comment]
Nevermind, I am dumb.

**Comment by funkynuggets** [comment]
will give it a quick look over real quick

**Comment by funkynuggets** [comment]
Gave a offline test, looks good.

**Comment by funkynuggets** [comment]
I CANT BELIEVE I FORGOT TO MERGE THIS AM I FUCKING STUPOID

**Pull request merged**
