### PR TITLE
H.E.C.U outfit (only assets and basic implementation)

### PR DESCRIPTION
**Pull request by OopsAllBrainWorms**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/brushtool/fpstation/blob/master/fpstation/README.md )

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

## Why It's Good For The Game

dreamseeker_2019-04-27_17-30-09
no changelog because this isn't available in game (yet) currently admeme only but this provides assets for anyone wanting to make the HECU unit as a deathsquad type.

### CODE REVIEW

**Comment by funkynuggets** [comment]
So, I was working on my end on this trying to add the HECU sounds as a vox type for them but it's such spaghetti code. Would you prefer it just being standard screams or me to actually make this thing?

**Comment by OopsAllBrainWorms** [comment]
> 
> 
> So, I was working on my end on this trying to add the HECU sounds as a vox type for them but it's such spaghetti code. Would you prefer it just being standard screams or me to actually make this thing?

up to you really

**Comment by funkynuggets** [comment]
> 
> 
> > So, I was working on my end on this trying to add the HECU sounds as a vox type for them but it's such spaghetti code. Would you prefer it just being standard screams or me to actually make this thing?
> 
> up to you really

I don't really mind doing either, but the vox one will delay me actually adding it as a spawnable thing

**Comment by OopsAllBrainWorms** [comment]
> 
> 
> > > So, I was working on my end on this trying to add the HECU sounds as a vox type for them but it's such spaghetti code. Would you prefer it just being standard screams or me to actually make this thing?
> > 
> > 
> > up to you really
> 
> I don't really mind doing either, but the vox one will delay me actually adding it as a spawnable thing

i mean i think adding the vox scream would be worth the wait imo.

**Comment by funkynuggets** [comment]
> 
> 
> > > > So, I was working on my end on this trying to add the HECU sounds as a vox type for them but it's such spaghetti code. Would you prefer it just being standard screams or me to actually make this thing?
> > > 
> > > 
> > > up to you really
> > 
> > 
> > I don't really mind doing either, but the vox one will delay me actually adding it as a spawnable thing
> 
> i mean i think adding the vox scream would be worth the wait imo.

There are 326 files that I have to code into a list manually and list their files seperately. This is going to take a decade, so I'm going to merge this in the meantime. I can't believe oyu've made me do this.

**Pull request merged**
