### PR TITLE
Botany changes & Additions + Cargo export changes (done merging stuff)

### PR DESCRIPTION
**Pull request by OopsAllBrainWorms**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/brushtool/fpstation/blob/master/fpstation/README.md )

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

## Why It's Good For The Game
dreamseeker_2019-04-23_15-25-53
out of date screenie above here's a more up to date one
dreamseeker_2019-04-24_16-45-58

Here you can the sprite of the moneycap seed, the harvest you get, and a moneycap in progress of it's growth cycle. Moneycaps contain 20% gold the same as golden apples. You get one random coin per moneycap. 

dreamseeker_2019-04-23_15-27-27
dreamseeker_2019-04-23_15-27-33
Here's the export values of coins from top left to bottom center. These changes allow botany to help out with cargo or if there's a willing RD they could grow a few money caps and send the money to them to be added to the scientific budget.

With the coin change alone this opens a bridge between cargo and science as an inspiring xenobiologist could make adamantine bars to be brought to the coin press on the mining station. 

This pr provides the path for interesting interactions now it is on the players to do it.

gave up on the other stuff *shrug* we good fam

### CODE REVIEW

**Comment by OopsAllBrainWorms** [comment]
oof travis doesn't like me

**Comment by jessicamaybe** [comment]
build failed because of something funky did. everything looks good to me.
please follow this changelog procedure and then we'll merge it
https://tgstation13.org/wiki/Guide_to_Changelogs

**Comment by funkynuggets** [comment]
Not merge ready? 

> 
> 
> build failed because of something funky did. everything looks good to me.
> please follow this changelog procedure and then we'll merge it
> https://tgstation13.org/wiki/Guide_to_Changelogs
build failed because byond is down, dum dum

**Comment by OopsAllBrainWorms** [comment]
@jessicamaybe Done. Also snuck in the bio bag of holding into the changelog since i didn't do a changelog then.

**Comment by jessicamaybe** [comment]
alright, this looks good, merging

**Pull request merged**
