### PR TITLE
Disables Supermatter delamination because power is over X

### PR DESCRIPTION
**Pull request by Toxici12i**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/brushtool/fpstation/blob/master/fpstation/README.md )

## Changelog
:cl:
del: The SM no longer delaminates because it is over the critical threshold. This was bad.
tweak: The SM no longer also spawns pyroclastic anomalies (both because it annoys ghosts if an engineer does a meme build, and because it spawns hostile mobs and lots of them)
/:cl:

## About The Pull Request
So far, this pull request disables delamination if the SM is over a certain EEV but not on fire, nor taking damage from any other source.

## Why It's Good For The Game
This was a feature designed to limit players in one of the least funny ways possible damnit.

### CODE REVIEW

**Comment by Toxici12i** [comment]
image
also improves supermatter critical MEEV statments. Works.

**Comment by Toxici12i** [comment]
all good, merge ready

**Comment by Toxici12i** [comment]
image
map file compile is not related

**Comment by funkynuggets** [comment]
lets fucking GO

**Pull request merged**
