### PR TITLE
Merchant Freighter, Expanded CC Dock + weapon drops

### PR DESCRIPTION
**Pull request by Weisyl**
Expanded CentCom's dock and added new random weapon spawns there for more round-end carnage. This also includes a small staging area for the shuttle engineers.
Picture: https://gyazo.com/182e5516a2263c9eb384f911aa9fd376

New Merchant Freighter which contains a whole ton of loot. Should only be used by admins (or reasonably trustworthy players) The freighter also includes turrets which will automatically fire freezing bolts at anyone in the vicinity.
Picture: https://gyazo.com/ac275f0f1d96d64eeb656139eb02f967

### CODE REVIEW

**Comment by funkynuggets** [comment]
Could you Modulize this? Would cause alot of conflict issues down the road.

**Comment by Weisyl** [comment]
> Could you Modulize this? Would cause alot of conflict issues down the road.

How would this be modulized? Haven't dealt with code and the like in a couple years

**Comment by Weisyl** [comment]
Actually, this'd mean placing the new code and objects in the /face folder and organized appropriately, right?

Edit: Done

**Comment by jessicamaybe** [comment]
When modifying maps, did you follow these requirements?
https://tgstation13.org/wiki/Map_Merger

**Comment by Weisyl** [comment]
> When modifying maps, did you follow these requirements?
> https://tgstation13.org/wiki/Map_Merger

All the edited maps were map merged, yeah

**Comment by jessicamaybe** [comment]
alright, looks good to me, I'll have funky review it and approve

**Review by funkynuggets — APPROVED** [review]
Everything looks good here. Would ask for a gibgun at central command just for the old time sake but otherwise we're good to go.

**Comment by Weisyl** [comment]
@Funkynuggets I can add that as a low chance to one of the weapon loot drops and also place one. Can do that with this PR or another one since this is already set.

**Pull request merged**
